signature.url=jdbc:db2://172.22.30.34:446/IASPBR
aloyal.url=jdbc:oracle:thin:@172.22.50.120:1521/pdbuc36
app.empresas.url=jdbc:sqlserver://172.22.50.212:1433;databaseName=IBKEmpData;encrypt=true;trustServerCertificate=true
cadencie.url=jdbc:oracle:thin:@172.22.50.122:1521/pdbuc36
app.personas.url=jdbc:sqlserver://172.22.50.212:1433;databaseName=IBKPerData;encrypt=true;trustServerCertificate=true
