<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>SignatureAutomation</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>SignatureAutomation</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <!--        JunitVersions           -->
        <junit.version>5.13.4</junit.version>
        <junitPlatform.version>1.13.4</junitPlatform.version>
        <!--        JunitVersions           -->
        <cucumber.version>7.27.0</cucumber.version>
        <selenium.version>4.35.0</selenium.version>
        <assertJ.version>3.27.4</assertJ.version>
        <webdrivermanager.version>6.2.0</webdrivermanager.version>
        <lombok.version>1.18.38</lombok.version>
        <log4j.version>2.25.1</log4j.version>
        <jcraft.version>0.1.55</jcraft.version>
        <maven.compiler.release>21</maven.compiler.release>
        <maven.compiler.plugin.version>3.13.0</maven.compiler.plugin.version>
        <!--        extentDepsVersions          -->
        <extent.reporter.Version>5.1.2</extent.reporter.Version>
        <tech.grasshopper.version>1.14.0</tech.grasshopper.version>
        <maven.surefire.plugin.version>3.5.2</maven.surefire.plugin.version>
        <!--        extentDepsVersions          -->
        <!--        Requests and GraphQL        -->
        <json.version>20250517</json.version>
        <!--        Requests and GraphQL        -->
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${assertJ.version}</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>${cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${junit.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${junit.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite</artifactId>
            <version>${junitPlatform.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-engine</artifactId>
            <version>${junitPlatform.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>${webdrivermanager.version}</version>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>
        <!--        ExtentReportDeps-->
        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>${extent.reporter.Version}</version>
        </dependency>
        <dependency>
            <groupId>tech.grasshopper</groupId>
            <artifactId>extentreports-cucumber7-adapter</artifactId>
            <version>${tech.grasshopper.version}</version>
        </dependency>
        <!--        ExtentReportDeps-->
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>${json.version}</version>
        </dependency>
        <dependency>
            <groupId>com.jcraft</groupId>
            <artifactId>jsch</artifactId>
            <version>${jcraft.version}</version>
        </dependency>
        <dependency>
            <groupId>com.banreservas</groupId>
            <artifactId>connexusdb</artifactId>
            <version>1.5.4</version>
        </dependency>
        <dependency>
            <groupId>com.banreservas</groupId>
            <artifactId>money</artifactId>
            <version>1.15.1</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>gitlab-maven</id>
            <url>https://gitlab.example.com/api/v4/groups/87721015/-/packages/maven</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>gitlab-maven</id>
            <url>https://gitlab.com/api/v4/groups/87721015/-/packages/maven</url>
        </pluginRepository>
    </pluginRepositories>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>com.banreservas</groupId>
                <artifactId>connexusdb-maven-plugin</artifactId>
                <version>1.2</version>
            </plugin>
        </plugins>
    </build>
</project>